# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EventsApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EventsApp
  pod 'Firebase/Core'
  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.7'

  target 'EventsApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EventsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
