fastlane_version '2.53.1'

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end


platform :ios do

	desc 'Fetch certificates and provisioning profiles'
	lane :certificates do
  		match(app_identifier: 'nl.socialbrothers.eventsapp', type: 'development', readonly: true)
		match(app_identifier: 'nl.socialbrothers.eventsapp', type: 'appstore', readonly: true)
	end

	desc 'Build the iOS application.'
	private_lane :build do
  		certificates
  		increment_build_number(xcodeproj: './ios/EventsApp.xcodeproj')
  		gym(scheme: 'name', project: './ios/EventsApp.xcodeproj')
	end

	desc 'Ship to Testflight.'
  		lane :beta do
    		build
    		pilot
    		commit_version_bump(message: 'Bump build', xcodeproj: './ios/EventsApp.xcodeproj')
    		push_to_git_remote
  	end
end

platform :android do
  # Android Lanes
end
